import "dotenv/config";
import createClient from "openapi-fetch";
import type { paths } from "./lib/api/melodi"; // generated by openapi-typescript

const client = createClient<paths>({
  baseUrl: "https://app.melodi.fyi/api/external",
});

export async function getThreads() {
  const {
    data, // only present if 2XX response
    error, // only present if 4XX or 5XX response
  } = await client.GET("/threads", {
    headers: {
      "api-key": process.env.MELODI_API_KEY,
    },
  });

  if (error) {
    console.log(error);
    return;
  }

  if (data) {
    console.log(data.rows.length);
    const firstThread = data.rows[0];

    if (firstThread) {
      console.log(firstThread.messages.length);

      if (firstThread.messages[0]) {
        console.log(firstThread.messages[0].type);
      }
    }
  }
}
